# Exported from Render on 2026-07-15T08:28:20Z
version: "1"
services:
- type: web
  name: pos-api
  runtime: node
  repo: https://github.com/Fres02/POS_Darimac_Tech_Task
  plan: free
  envVars:
  - key: WEB_ORIGIN
    sync: false
  - key: RESEND_FROM_EMAIL
    sync: false
  - key: RESEND_API_KEY
    sync: false
  - key: SUPABASE_PUBLISHABLE_KEY
    sync: false
  - key: SUPABASE_SERVICE_ROLE_KEY
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: DATABASE_URL
    sync: false
  - key: NODE_ENV
    value: production
  - key: NODE_VERSION
    value: "22"
  region: singapore
  buildCommand: pnpm install --frozen-lockfile --prod=false && pnpm --filter @pos/api run typecheck
  startCommand: pnpm --filter @pos/api start
  healthCheckPath: /health
  autoDeployTrigger: commit
